export default function Grid() {
  return (
    <div className="grid h-full w-full grid-cols-8">
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
      <div className="border" />
    </div>
  );
}
